#!/usr/bin/env bash

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $POSTGRES_WORKER_USER WITH PASSWORD '$POSTGRES_WORKER_PASSWORD';
    CREATE USER $POSTGRES_UI_USER WITH PASSWORD '$POSTGRES_UI_PASSWORD';

    GRANT USAGE ON SCHEMA $SCHEMA_PUBIC TO $POSTGRES_WORKER_USER;
    GRANT INSERT, UPDATE, DELETE, SELECT ON ALL TABLES IN SCHEMA $SCHEMA_PUBIC TO $POSTGRES_WORKER_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA $SCHEMA_PUBIC GRANT INSERT, UPDATE, DELETE, SELECT ON TABLES TO $POSTGRES_WORKER_USER;


    GRANT USAGE ON SCHEMA $SCHEMA_PUBIC TO $POSTGRES_UI_USER;
    GRANT SELECT ON ALL TABLES IN SCHEMA $SCHEMA_PUBIC TO $POSTGRES_UI_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA  $SCHEMA_PUBIC GRANT SELECT ON TABLES TO $POSTGRES_UI_USER;

EOSQL
